### ISSUE TITLE
Unable to use default_type for NXOS netconf

### ISSUE THREAD

**Issue by sanjmonkey** [scrapli/scrapli_netconf#128]
**Describe the bug**
When specifying `default_type` in `get_config()` calls against NXOS (only 9.3.(10) tested so far), scrapli_netconf raises a `CapabilityNotSupported` error at [base_driver.py#L530](https://github.com/scrapli/scrapli_netconf/blob/932575cad5b8b841553eea1958e2ba3bdbf85260/scrapli_netconf/driver/base_driver.py#L530)

This is because NXOS returns the string in its server capabilities: `urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=report-all`

But the comparison in [base_driver.py#L525](https://github.com/scrapli/scrapli_netconf/blob/932575cad5b8b841553eea1958e2ba3bdbf85260/scrapli_netconf/driver/base_driver.py#L525) looks specifically for `urn:ietf:params:netconf:capability:with-defaults:1.0` in the list of server capabilities

**To Reproduce**
```
NXOS_NS_FILTER = '<System xmlns="http://cisco.com/ns/yang/cisco-nx-os-device"/>'
conn = NetconfDriver(**nxos_box)
conn.open()
response = conn.get_config(filter_=NXOS_NS_FILTER, default_type="trim")
```

**Expected behavior**
Manually querying the box for `?with-defaults=trim` shows that it does appear to "support" with-defaults and does indeed return only trimmed results (similarly for "explicit")... though cisco.com has little documentation or examples to support my findings :).  So I would ideally like it not throw an exception and to have the "trim" config results returned

**Suggestion**
Perhaps its enough to look over each server capability string in the list, looking for at least `urn:ietf:params:netconf:capability:with-defaults:1.0` in one of those strings, to conclude with-defaults is supported?

**Comment by carlmontanari** [comment]
👋 hey @sanjmonkey thanks for raising this! your suggestion seems reasonable! would you be interesting in throwing together a pr for it?

thanks!

**Comment by carlmontanari** [comment]
closing this out, will follow up in the pr! thanks again!
