### ISSUE TITLE
etree.XMLSyntaxError: PCDATA invalid Char

### ISSUE THREAD

**Issue by hardev20** [scrapli/scrapli_netconf#18]
Hi, 

I have tried pulling ios XR configuration data using scrapli netconf after connecting the device but it has returned the error - lxml.etree.XMLSyntaxError: PCDATA invalid Char value 8, line 395, column 19. I have attached the full trace with this case. 

[XML Syntax Error.txt](https://github.com/scrapli/scrapli_netconf/files/5556207/XML.Syntax.Error.txt)

Commands were tried step by step using ipython and attached file shows relevant output as well.

I have also tried running the following script and resulted in similar error message and the DEBUG logs are attached as well.

```
from scrapli_netconf.driver import NetconfScrape

from bs4 import BeautifulSoup

import logging
logging.basicConfig(filename="scrapli.log", level=logging.INFO)
logger = logging.getLogger("scrapli")

my_device = {
    "host": "192.168.0.111",
    "auth_username": "test",
    "auth_password": "test123",
    "auth_strict_key": False,
    "ssh_config_file": True,
    "port": 830,
    "strip_namespaces": True,
}

conn = NetconfScrape(**my_device)
conn.open()

response = conn.get_config(source="running")
# print the raw XML to the screen
print(BeautifulSoup(result.result, "xml").prettify())
```

[scrapli.log](https://github.com/scrapli/scrapli_netconf/files/5556326/scrapli.log)

Appreciate if you could please help me to fix this problem. Many thanks.

**Comment by hardev20** [comment]
[DEBUG.log](https://github.com/scrapli/scrapli_netconf/files/5556400/DEBUG.log)

I have run the same script with logging level as DEBUG for capturing additional information.

**Comment by carlmontanari** [comment]
Hey @hardev20  thanks for opening this and the logs. Found a hopefully easy fix (this is due to non "standard" unicode characters in one of your descriptions) but haven't had time to test it thoroughly yet.

I've pushed this to develop branch though so if you can give it a shot and let us know if it fixes things that would be great! You can install the develop branch like so: `pip install -e git+https://github.com/scrapli/scrapli_netconf.git@develop#egg=scrapli_netconf
`

Carl

**Comment by hardev20** [comment]
That was really a magic! Just installed the version of the scrapli_netconf build you have sent me and got a clean XML config file back from the IOS XR router. 

I am highly encouraged now to learn more and develop scripts for my work. Thank you very much for your help. Cheers

Regards,
Rajesh Sivaraj

On 18 Nov 2020, at 00:48, Carl Montanari <notifications@github.com> wrote:


Hey @hardev20 <https://github.com/hardev20> thanks for opening this and the logs. Found a hopefully easy fix (this is due to non "standard" unicode characters in one of your descriptions) but haven't had time to test it thoroughly yet.

I've pushed this to develop branch though so if you can give it a shot and let us know if it fixes things that would be great! You can install the develop branch like so: pip install -e git+https://github.com/scrapli/scrapli_netconf.git@develop#egg=scrapli_netconf

Carl

**Comment by carlmontanari** [comment]
Awesome! I'll test this out more before it goes to master and pypi, but I think it should be good to go. I'll go ahead and close this now, feel free to reopen if same issue pops up again.

Thanks for opening and the logs and such!

Carl
