### ISSUE TITLE
Feature request: add with-defaults element option to get_config

### ISSUE THREAD

**Issue by kn-winter** [scrapli/scrapli_netconf#29]
Hello.  This is a feature request to add an option to get_config so you can specify the `with-defaults` element as in RFC 6243.  This is helpful when pulling a full configuration as in some cases, you want to see the vendor default values.

A typical get_config from running would be:
```
<get-config>
  <source>running</source>
</getconfig>
```

When adding a `with-defaults` element with a mode of `report-all`, it would be:
```
<get-config>
  <source>running</source>
  <with-defaults xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">report-all</with-defaults>
</getconfig>
```

I'm trying it out locally here https://github.com/scrapli/scrapli_netconf/compare/develop...kn-winter:add-with-default

Let me know what you think.  Thanks.

Khiem

**Comment by carlmontanari** [comment]
Hey @kn-winter  -- sounds like probably a good addition! I'll hopefully have some time to take a look this weekend!

Thanks for opening this!

Carl

**Comment by carlmontanari** [comment]
Going to close this out now and we can work on this in #33 

Unfortunately this weekend may be a bit busy but I swear we'll get that tweaked and merged one of these days :D
