### ISSUE TITLE
ModuleNotFoundError: No module named 'scrapli_netconf.driver'; 'scrapli_netconf' is not a package

### ISSUE THREAD

**Issue by muhammad-rafi** [scrapli/scrapli_netconf#54]
I am not sure why I am seeing this, it was working fine a day ago and suddenly this module error started coming through, I tried to uninstall and install the packages back again no difference, scratching my head to find a way through, it could be simple or really a bug ? 

I am using CentOS7 and installed the packages via 
pip3 install scrapli_netconf

Just F.Y.I scrapli core is working absolutely fine and no issues there.

Thanks, 
-Rafi

**Comment by carlmontanari** [comment]
Do you happen to have a file named `scrapli_netconf` in your working directory? sounds like that would be the most likely culprit. if thats not the case going to need more info probably, and probably for you to re-create in a fresh virtual environment w/ a minimum reproducible example so I can see first hand what's going on.

Carl

**Comment by muhammad-rafi** [comment]
ahh, I think I have over worked last night, I did create a python script with the same name without realizing that I am using the same as package name and should have pointed that out without bothering you :) 

Thank you Carl, appreciated dealing with my ignorance

**Comment by carlmontanari** [comment]
hah no worries, we've all been there!
