### ISSUE TITLE
Add support for raise_on_error driver argument

### ISSUE THREAD

**Issue by dmulyalin** [scrapli/scrapli_netconf#90]
Currently, if RPC operation fails, Scrapli-netconf `result` attribute contains rpc-error content, `failed` attribute also set to true. When doing many operations in a sequence, need to check `failed` for each and every request. 

It would be good to have a raise_on_error type of argument supported by NetconfDriver, so that Scrapli will raise and error if operation fails e.g.

```
from scrapli_netconf.driver import NetconfDriver

my_device = {
    "host": "172.18.0.13",
    "auth_username": "vrnetlab",
    "auth_password": "VR-netlab9",
    "auth_strict_key": False,
    "port": 830,
    "raise_on_error": True
}

conn = NetconfDriver(**my_device)

# current way of doing it:
try:
    r = conn.lock()
    if r.failed:
        raise RuntimeError(r.result)
    r = conn.discard()    
    if r.failed:
        raise RuntimeError(r.result)
    r = conn.edit_config(config="...", target="candidate")
    if r.failed:
        raise RuntimeError(r.result)
    r = conn.validate()
    if r.failed:
        raise RuntimeError(r.result)
    r = conn.commit()
    if r.failed:
        raise RuntimeError(r.result)
    r = conn.unlock()
    if r.failed:
        raise RuntimeError(r.result)
except:
    "catch error and do something"

# desired way if raise_on_error will be supported
try:
    r = conn.lock()
    r = conn.discard()    
    r = conn.edit_config(config="...", target="candidate")
    r = conn.validate()
    r = conn.commit()
    r = conn.unlock()
except:
    "catch error and do something"
```
in such a case wrapping all the operations in try/except block will be able to catch an error for any operation without the need to explicitly check `failed` status.

or support raise_on_error argument for operation e.g.
```
response = conn.get_config(source="running", raise_on_error=True)
```

**Comment by carlmontanari** [comment]
Have you seen [this](https://github.com/carlmontanari/scrapli/blob/master/scrapli/response.py#L211)? I wonder if that gets you at least half way to what you are after? 

That plus something maybe like this:

```python
ops = [
    partial(conn.lock)
    partial(conn.discard)
    ...
]

for op in ops:
    r = op()
    r.raise_for_status()
```

I don't think I love the idea of adding a rase on error kind of thing when there is already the raise for status method. I could maybe be convinced but maybe/hopefully raise for status + some partial magic gets you close to what you are looking for?

**Comment by dmulyalin** [comment]
`raise_for_status` looks like what I need, but seems that is raises without adding information for the error, would it make sense to update it to something like this:

```
    def raise_for_status(self, error_message="") -> None:
        """
...
        """
        if self.failed:
            raise ScrapliCommandFailure(error_message)
```

notice the addition of `error_message`, so that parent program can do something like:
```
r = conn.lock()
r.raise_for_status(r.result)
```

**Comment by carlmontanari** [comment]
Yeah I think that is a great idea -- especially in scrapli_netconf where we can actually have useful rpc errors reported. Will keep this open till I get around to it :) I should be able to get to it before the next release!

**Comment by carlmontanari** [comment]
Hey @dmulyalin !

Check out #92 and lemme know what you think? I also realized that the response object already has a `error_messages` attribute (I totally forgot about this till looking at this just now!). Between the raise_for_status, the error_messages, and the new addition of the exception message in #92 I think/hope this looks good -- what do you think?

Carl

**Comment by dmulyalin** [comment]
Looks great, thank you for investing your time into it.

**Comment by carlmontanari** [comment]
Np, thanks for raising this and your help!
